version: '3.8'

services:
  personamap:
    build:
      context: .
      target: development
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:///instance/personamap.db
      - SECRET_KEY=dev-secret-key-change-in-production
      - AI_ENABLED=false
      - AI_ANALYSIS_MODE=keyword
    volumes:
      - .:/app
      - personamap_instance:/app/instance
      - personamap_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL database for production-like development
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: personamap
      POSTGRES_USER: personamap
      POSTGRES_PASSWORD: personamap_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - postgres

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - redis

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - personamap
    restart: unless-stopped
    profiles:
      - nginx

volumes:
  personamap_instance:
  personamap_logs:
  postgres_data:
  redis_data:

networks:
  default:
    name: personamap_network
